### PR TITLE
Fix hello_xr when running under Linux OpenGL X11

### LINKED ISSUE #41: hello_xr Wayland graphics bindings are improperly initialized
See https://github.com/KhronosGroup/OpenXR-SDK/blob/master/src/tests/hello_xr/graphicsplugin_opengl.cpp#L106-L118

Wayland/xcb/xlib connections are all initialized to nonsense, and remaining fields (where applicable) are left entirely uninitialized. Testing on Monado seems to work anyway, at least on xlib, which further raises the question of whether this information is actually needed.

### PR DESCRIPTION
**Pull request by SamanthaBowen**
This relates to #41, but only fixes it when using Xlib and XCB, not for Wayland. This also fixes a separate issue I had on my own machine with Monado's OpenGL graphics requirements.

### CODE REVIEW

File: src/common/gfxwrapper_opengl.h [hunk 1]
```diff
@@ -186,7 +186,7 @@ Platform headers / declarations
 #elif defined(OS_LINUX)
 
 #define OPENGL_VERSION_MAJOR 4
-#define OPENGL_VERSION_MINOR 3
+#define OPENGL_VERSION_MINOR 5
```
Comment (rpavlik) [inline src/common/gfxwrapper_opengl.h:189]: Did it not work with 4.3? I suspect 4.3 should still work since I've used it locally without it failing.

**Review by rpavlik — APPROVED** [review]
Thanks for your contribution, this looks good to me! I did have one question, but it can be addressed in a follow-up PR if required.

File: src/common/gfxwrapper_opengl.h (hunk 1 above)
Comment (SamanthaBowen) [reply src/common/gfxwrapper_opengl.h:189]: When I change it back to 4.3, this is what I get when I run `./hello_xr -g OpenGL`:
```
[17:36:07.783][Info   ] Press any key to shutdown...
[17:36:07.803][Info   ] Available Layers: (0)
[17:36:07.811][Info   ] Instance RuntimeName=Monado(XRT) by Collabora et al RuntimeVersion=0.1.42
[17:36:07.811][Info   ] Available View Configuration Types: (1)
[17:36:07.811][Info   ] Available Environment Blend Mode count : (1)
[17:36:07.811][Info   ] Environment Blend Mode (XR_ENVIRONMENT_BLEND_MODE_OPAQUE) : (Selected)
[17:36:07.870][Error  ] Runtime does not support desired Graphics API and/or version
    Source: ../../src/tests/hello_xr/graphicsplugin_opengl.cpp:111
```
The exception thrown in `graphicsplugin_opengl.cpp` is caused by checking the active OpenGL version against the minimum version given by `xrGetOpenGLGraphicsRequirementsKHR`. Looking at the Monado source code at <https://gitlab.freedesktop.org/monado/monado>, `oxr_xrGetOpenGLGraphicsRequirementsKHR` calls `xrt_gfx_gl_get_versions`, which hardcodes 4.5 as the minimum version. This is consistent with my testing since 4.4 doesn't work either on my machine.

What version of Monado are you using?

Comment (rpavlik) [reply src/common/gfxwrapper_opengl.h:189]: oh, interesting.  I'm using something close to master. @wallbraker - any particular reason we need 4.5? or would 4.3 suffice? (I don't remember if Monado's use of 4.5 was just "pick a number out of thin air")

**Comment by rpavlik** [comment]
Hmm. When I pull this into the internal repo with CI, it fails during the xcb-backend build of the exported source. (Don't know why it doesn't fail with the normal source)

```
FAILED: /usr/bin/c++   -DOPENXR_HAVE_COMMON_CONFIG -DOS_LINUX_XCB_GLX -DXR_OS_LINUX -DXR_USE_GRAPHICS_API_OPENGL -DXR_USE_PLATFORM_XCB -DXR_USE_TIMESPEC -I../src/../include -I../src -Isrc/tests/hello_xr -I../src/common -I../include -Iinclude -I../external/include -fPIE   -Wall -std=gnu++14 -MMD -MT src/tests/hello_xr/CMakeFiles/hello_xr.dir/graphicsplugin_opengl.cpp.o -MF src/tests/hello_xr/CMakeFiles/hello_xr.dir/graphicsplugin_opengl.cpp.o.d -o src/tests/hello_xr/CMakeFiles/hello_xr.dir/graphicsplugin_opengl.cpp.o -c ../src/tests/hello_xr/graphicsplugin_opengl.cpp
In file included from ../src/tests/hello_xr/graphicsplugin_opengl.cpp:9:0:
../src/common/xr_linear.h:24:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic ignored "-Wunused-function"
 ^
../src/tests/hello_xr/graphicsplugin_opengl.cpp: In member function ‘virtual void {anonymous}::OpenGLGraphicsPlugin::InitializeDevice(XrInstance, XrSystemId)’:
../src/tests/hello_xr/graphicsplugin_opengl.cpp:124:55: error: ‘struct ksGpuContext’ has no member named ‘connection’
         m_graphicsBinding.connection = window.context.connection;
                                                       ^
../src/tests/hello_xr/graphicsplugin_opengl.cpp:125:57: error: ‘struct ksGpuContext’ has no member named ‘screenNumber’
         m_graphicsBinding.screenNumber = window.context.screenNumber;
                                                         ^
../src/tests/hello_xr/graphicsplugin_opengl.cpp:126:55: error: ‘struct ksGpuContext’ has no member named ‘fbconfigid’
         m_graphicsBinding.fbconfigid = window.context.fbconfigid;
                                                       ^
../src/tests/hello_xr/graphicsplugin_opengl.cpp:129:55: error: invalid conversion from ‘GLXContext {aka __GLXcontextRec*}’ to ‘xcb_glx_context_t {aka unsigned int}’ [-fpermissive]
         m_graphicsBinding.glxContext = window.context.glxContext;
                                                       ^
```

Probably a define issue related to gfxwrapper. I'll dig into it further tomorrow.

File: src/common/gfxwrapper_opengl.h (hunk 1 above)
Comment (rpavlik) [reply src/common/gfxwrapper_opengl.h:189]: (does this mean I can't use OpenGL 1.1 or 2.1 with Monado? That would be weird...)
